# Adapted from revdiff's Gruvbox theme.
# Original author: umputun. See ../REVDIFF-LICENSE.
name = "gruvbox"
syntax_style = "gruvbox"

[palette]
background = "#282828"
foreground = "#EBDBB2"
muted = "#928374"
border = "#504945"
border_focus = "#FABD2F"
selection_background = "#FABD2F"
selection_foreground = "#282828"
accent = "#FABD2F"
directory = "#FABD2F"
heading = "#FE8019"
link = "#B8BB26"
code = "#B8BB26"
status = "#FABD2F"
